import localFont from "next/font/local";
import "./globals.css";
import Mainsidebar from "./Components/Mainsidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ display: "flex", height: "100vh", overflow: "hidden" }}>
          <Mainsidebar />
          <div style={{ flex: 1, overflowY: "auto" }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
